= The Secret of Monkey Island dans le navigateur
:hp-tags: dart, dartlang, SCUMM, ScummVM, SCUMMDart
:published_at: 2013-03-19

Il y a environ un an, pour apprendre http://www.dartlang.org/[Dart], je me suis lancé dans un projet un peu fou : réécrire un moteur http://en.wikipedia.org/wiki/SCUMM[SCUM] en Dart en portant le code source du projet open-source https://github.com/scummvm/scummvm[ScummVM]. L'objectif est de pouvoir jouer à Monkey Island (version française CD, SCUMM version 5) directement dans le navigateur.

J'ai fait une longue pause en attendant que le langage se stabilise et j'ai repris le code récemment. Voilà une courte vidéo (désolé pour la faible qualité, c'est mon premier post sur youtube) qui montre ce qui fonctionne pour le moment (pour faire court, le générique du jeu).

video::UkZ6v8LHbaU[youtube, width=640, height=480]

Sur la vidéo on voit qu'il reste quelques problèmes :

- un problème de palette de couleur pour les crédits : ils sont écrits en bleu, ils devraient être magenta ;
- c'est lent. À mon avis, ce problème est lié à Dartium ou au debugger du Dart Editor. Après compilation avec dart2js ça semble beaucoup plus rapide mais le Javascript produit contient des erreurs.

Le code n'est pas encore publié mais sera rapidement https://github.com/jcsirot/SCUMM-Dart[disponible sur GitHub] où pour le moment est hébergé l'ancienne version.